M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Wed Oct  7 19:45:54 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-07T19:45:54+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X113.97Y-97.46
X115.24Y-49.2
X166.04Y-64.44
X166.04Y-92.38
M30
