M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Wed Oct  7 20:12:23 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-07T20:12:23+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X126.4Y-180.25
T2
X104.0Y-104.0
X104.0Y-168.0
X180.0Y-104.0
X195.5Y-191.5
M30
